### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/python-noontide#1]
- [ ] some images fail to display, fix download and rename
- [ ] remove the search box or implement it :100: 
- [ ] add atom feed generator
